Repository Plume-org/Plume, pull requests merged in 2018-07, with the labels that each got.

#111 Form validation
  Cargo.lock
  Cargo.toml
  migrations/2018-04-22-093322_create_instances/up.sql
  po/plume.pot
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/posts.rs
  src/routes/session.rs
  src/routes/user.rs
  templates/blogs/new.html.tera
  templates/macros.html.tera
  templates/posts/new.html.tera
  templates/session/login.html.tera
  templates/users/new.html.tera
Labels: A: Front-End, A: Security, C: Enhancement, S: Ready for review

#104 New forms style
  static/main.css
Labels: A: Front-End, C: Enhancement, Design, S: Ready for review

#154 Fix a bug in mentions
  plume-common/src/utils.rs
  plume-models/src/comments.rs
Labels: A: Backend, A: Federation, C: Bug, S: Ready for review

#158 Show the total number of article on a blog
  plume-models/src/posts.rs
  po/plume.pot
  src/routes/blogs.rs
  templates/blogs/details.html.tera
Labels: A: Front-End, C: Enhancement, S: Ready for review
