Repository Plume-org/Plume, pull requests merged in 2018-10, with the labels that each got.

#250 Add link underline for main body
  static/css/main.css
Labels: A: Front-End, Design, S: Ready for review

#249 Delete posts when deleting account
  plume-models/src/users.rs
Labels: A: Backend, S: Ready for review

#261 CLI tools
  Cargo.lock
  Cargo.toml
  Dockerfile
  docs/CLI.md
  docs/INSTALL.md
  docs/UPDATE.md
  plume-cli/Cargo.toml
  plume-cli/src/instance.rs
  plume-cli/src/main.rs
  plume-cli/src/users.rs
  src/main.rs
  src/setup.rs
Labels: A: Backend, C: Feature, S: Ready for review

#266 Change default license to CC-BY-SA
  docs/CLI.md
  migrations/postgres/2018-10-06-161151_change_default_license/down.sql
  migrations/postgres/2018-10-06-161151_change_default_license/up.sql
  migrations/sqlite/2018-10-06-161156_change_default_license/down.sql
  migrations/sqlite/2018-10-06-161156_change_default_license/up.sql
  plume-cli/src/instance.rs
  plume-models/src/posts.rs
  src/routes/posts.rs
Labels: A: Backend, C: Enhancement, S: Ready for review

#271 Update French translation
  po/fr.po
Labels: A: I18N, C: Enhancement

#276 Update de.po
  po/de.po
Labels: A: I18N, C: Enhancement

#256 Verify activity's signature
  plume-common/src/activity_pub/mod.rs
  plume-common/src/activity_pub/request.rs
  plume-common/src/activity_pub/sign.rs
  plume-models/src/blogs.rs
  plume-models/src/headers.rs
  plume-models/src/lib.rs
  plume-models/src/users.rs
  src/routes/instance.rs
  src/routes/user.rs
Labels: A: Security, S: Ready for review

#281 Panic less and with better messages
  plume-cli/src/main.rs
  plume-common/src/activity_pub/inbox.rs
  plume-common/src/activity_pub/mod.rs
  plume-common/src/activity_pub/request.rs
  plume-common/src/activity_pub/sign.rs
  plume-models/src/blogs.rs
  plume-models/src/comments.rs
  plume-models/src/follows.rs
  plume-models/src/instance.rs
  plume-models/src/lib.rs
  plume-models/src/likes.rs
  plume-models/src/medias.rs
  plume-models/src/mentions.rs
  plume-models/src/notifications.rs
  plume-models/src/posts.rs
  plume-models/src/reshares.rs
  plume-models/src/tags.rs
  plume-models/src/users.rs
  src/api/posts.rs
  src/inbox.rs
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/errors.rs
  src/routes/instance.rs
  src/routes/likes.rs
  src/routes/medias.rs
  src/routes/posts.rs
  src/routes/reshares.rs
  src/routes/session.rs
  src/routes/tags.rs
  src/routes/user.rs
Labels: A: Backend, C: Enhancement, S: Ready for review

#282 Add support for blog deletion
  plume-models/src/blogs.rs
  po/en.po
  po/fr.po
  po/gl.po
  po/nb.po
  po/pl.po
  po/plume.pot
  src/main.rs
  src/routes/blogs.rs
  templates/blogs/details.html.tera
Labels: A: Backend, C: Enhancement, S: Ready for review

#283 Support hashtags
  migrations/postgres/2018-10-20-164036_fix_hastag_typo/down.sql
  migrations/postgres/2018-10-20-164036_fix_hastag_typo/up.sql
  migrations/sqlite/2018-10-20-164036_fix_hastag_typo/down.sql
  migrations/sqlite/2018-10-20-164036_fix_hastag_typo/up.sql
  plume-common/src/utils.rs
  plume-models/src/comments.rs
  plume-models/src/instance.rs
  plume-models/src/schema.rs
  plume-models/src/tags.rs
  po/en.po
  po/fr.po
  po/gl.po
  po/nb.po
  po/pl.po
  po/plume.pot
  src/routes/comments.rs
  src/routes/posts.rs
  src/routes/tags.rs
  templates/posts/details.html.tera
  templates/tags/index.html.tera
Labels: A: Backend, C: Feature, S: Ready for review

#293 Fix editor auto-expansion
  static/js/autoExpand.js
  templates/posts/details.html.tera
  templates/posts/new.html.tera
Labels: A: Front-End, C: Bug, S: Ready for review
