Repository Plume-org/Plume, pull requests merged in 2018-11, with the labels that each got.

#308 Add support for CW in comments
  src/routes/comments.rs
  src/routes/posts.rs
  static/css/main.css
  templates/macros.html.tera
  templates/posts/details.html.tera
Labels: A: Backend, A: Federation, A: Front-End, C: Enhancement, S: Ready for review

#311 Correct Gentoo emerge instructions
  docs/INSTALL.md
Labels: A: Docs, C: Enhancement

#316 Decode unfollow activities in inbox properly
  src/inbox.rs
Labels: A: Federation, C: Bug, S: Ready for review

#315 Set Content-Type for ActivityPub request to correct value.
  plume-common/src/activity_pub/mod.rs
  plume-common/src/activity_pub/request.rs
Labels: A: Federation, C: Bug, S: Ready for review

#322 Run cargo clippy on whole project
  plume-cli/src/instance.rs
  plume-cli/src/users.rs
  plume-common/src/activity_pub/inbox.rs
  plume-common/src/activity_pub/mod.rs
  plume-common/src/activity_pub/request.rs
  plume-common/src/activity_pub/sign.rs
  plume-common/src/utils.rs
  plume-models/src/api_tokens.rs
  plume-models/src/apps.rs
  plume-models/src/blogs.rs
  plume-models/src/comments.rs
  plume-models/src/follows.rs
  plume-models/src/follows.rs.orig
  plume-models/src/instance.rs
  plume-models/src/lib.rs
  plume-models/src/likes.rs
  plume-models/src/medias.rs
  plume-models/src/mentions.rs
  plume-models/src/notifications.rs
  plume-models/src/posts.rs
  plume-models/src/reshares.rs
  plume-models/src/tags.rs
  plume-models/src/users.rs
  src/api/mod.rs
  src/inbox.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/instance.rs
  src/routes/likes.rs
  src/routes/medias.rs
  src/routes/notifications.rs
  src/routes/posts.rs
  src/routes/reshares.rs
  src/routes/session.rs
  src/routes/user.rs
  src/routes/well_known.rs
Labels: A: Backend, S: Ready for review
