Repository Plume-org/Plume, pull requests merged in 2018-09, with the labels that each got.

#180 New mobile menu
  .gitignore
  static/images/boxicon-menu.svg
  static/main.css
  templates/base.html.tera
Labels: A: Front-End, C: Enhancement, Design, S: Ready for review

#212 Add webapp manifest
  src/main.rs
  src/routes/instance.rs
  templates/base.html.tera
Labels: A: Front-End, C: Feature

#238 Fix CSRF issues
  po/gl.po
  src/routes/instance.rs
  src/routes/medias.rs
  src/routes/posts.rs
  src/routes/user.rs
  static/css/main.css
  templates/instance/list.html.tera
  templates/instance/users.html.tera
  templates/medias/details.html.tera
  templates/posts/details.html.tera
  templates/users/edit.html.tera
  templates/users/header.html.tera
Labels: A: Backend, A: Security, S: Ready for review
