Repository Plume-org/Plume, pull requests merged in 2018-12, with the labels that each got.

#324 Add a search engine into Plume
  .gitignore
  Cargo.lock
  Cargo.toml
  plume-cli/src/main.rs
  plume-cli/src/search.rs
  plume-models/Cargo.toml
  plume-models/src/blogs.rs
  plume-models/src/lib.rs
  plume-models/src/posts.rs
  plume-models/src/search/mod.rs
  plume-models/src/search/query.rs
  plume-models/src/search/searcher.rs
  plume-models/src/search/tokenizer.rs
  plume-models/src/users.rs
  src/api/posts.rs
  src/inbox.rs
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/instance.rs
  src/routes/likes.rs
  src/routes/mod.rs
  src/routes/posts.rs
  src/routes/reshares.rs
  src/routes/search.rs
  src/routes/user.rs
  templates/macros.html.tera
  templates/search/index.html.tera
  templates/search/result.html.tera
Labels: A: Backend, C: Feature, S: Ready for review

#343 License federation
  plume-common/src/activity_pub/mod.rs
  plume-models/src/posts.rs
  po/de.po
  po/en.po
  po/fr.po
  po/gl.po
  po/it.po
  po/ja.po
  po/nb.po
  po/pl.po
  po/plume.pot
  po/ru.po
  src/routes/posts.rs
  src/routes/user.rs
  templates/posts/details.rs.html
  templates/posts/new.rs.html
Labels: A: Federation, A: Front-End, C: Enhancement, S: Ready for review

#342 Add some constraint at database level
  migrations/postgres/2018-12-08-175515_constraints/down.sql
  migrations/postgres/2018-12-08-175515_constraints/up.sql
  migrations/sqlite/2018-12-08-182930_constraints/down.sql
  migrations/sqlite/2018-12-08-182930_constraints/up.sql
  plume-models/src/blogs.rs
  plume-models/src/medias.rs
  plume-models/src/search/mod.rs
  plume-models/src/users.rs
Labels: A: Backend, C: Enhancement, S: Ready for review

#351 Remove useless pagination routes
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/instance.rs
  src/routes/likes.rs
  src/routes/mod.rs
  src/routes/notifications.rs
  src/routes/posts.rs
  src/routes/reshares.rs
  src/routes/search.rs
  src/routes/session.rs
  src/routes/tags.rs
  src/routes/user.rs
  templates/base.rs.html
  templates/blogs/details.rs.html
  templates/instance/admin.rs.html
  templates/instance/federated.rs.html
  templates/instance/feed.rs.html
  templates/instance/index.rs.html
  templates/instance/list.rs.html
  templates/instance/local.rs.html
  templates/instance/users.rs.html
  templates/partials/post_card.rs.html
  templates/posts/details.rs.html
  templates/users/dashboard.rs.html
  templates/users/details.rs.html
  templates/users/followers.rs.html
Labels: A: Backend, C: Enhancement, S: Ready for review

#344 Count items in database as much as possible
  plume-models/src/blogs.rs
  plume-models/src/comments.rs
  plume-models/src/db_conn.rs
  plume-models/src/lib.rs
  plume-models/src/notifications.rs
  plume-models/src/posts.rs
  plume-models/src/users.rs
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/instance.rs
  src/routes/notifications.rs
  src/routes/posts.rs
  src/routes/user.rs
  templates/blogs/details.rs.html
  templates/instance/about.rs.html
  templates/instance/index.rs.html
  templates/partials/instance_description.rs.html
  templates/posts/details.rs.html
Labels: A: Backend, C: Enhancement, S: Ready for review

#355 Use SCSS
  .gitignore
  Cargo.lock
  Cargo.toml
  build.rs
  static/css/_article.scss
  static/css/_forms.scss
  static/css/_global.scss
  static/css/_header.scss
  static/css/_variables.scss
  static/css/main.css
  static/css/main.scss
Labels: A: Front-End, C: Enhancement, S: Ready for review

#362 Remove ap_url from mention
  migrations/postgres/2018-12-17-180104_mention_no_ap_url/down.sql
  migrations/postgres/2018-12-17-180104_mention_no_ap_url/up.sql
  migrations/sqlite/2018-12-17-180104_mention_no_ap_url/down.sql
  migrations/sqlite/2018-12-17-180104_mention_no_ap_url/up.sql
  plume-models/src/mentions.rs
  plume-models/src/schema.rs
Labels: A: Backend, S: Ready for review

#357 Fix some federation issues
  plume-common/src/utils.rs
  plume-models/src/comments.rs
  plume-models/src/follows.rs
  plume-models/src/instance.rs
  plume-models/src/posts.rs
  plume-models/src/users.rs
  src/inbox.rs
  src/routes/comments.rs
  src/routes/posts.rs
  src/routes/user.rs
Labels: A: Federation, S: Ready for review

#369 Give reshare and like ap_url before inserting
  plume-models/src/likes.rs
  plume-models/src/reshares.rs
  src/routes/likes.rs
  src/routes/reshares.rs
Labels: A: Backend, C: Bug, S: Ready for review

#363 Allow for comment deletion
  plume-models/src/comments.rs
  src/inbox.rs
  src/main.rs
  src/routes/comments.rs
  static/css/_article.scss
  static/css/feather.css
  templates/partials/comment.rs.html
  templates/posts/details.rs.html
Labels: A: Federation, A: Front-End, C: Feature, S: Ready for review

#372 Use Route159 for comment deletion button
  static/css/_article.scss
Labels: A: Front-End, C: Enhancement, S: Ready for review

#370 An attempt to fix disorted submit button on mobile devices like iPhone - please review
  static/css/_forms.scss
Labels: A: Front-End, C: Bug

#307 Post creation API
  Cargo.lock
  plume-api/Cargo.toml
  plume-api/src/lib.rs
  plume-api/src/posts.rs
  plume-models/Cargo.toml
  plume-models/src/lib.rs
  plume-models/src/posts.rs
  src/api/posts.rs
  src/main.rs
Labels: A: API, A: Backend, C: Enhancement, S: Ready for review

#376 Change title from Edit account to Create account
  templates/users/new.rs.html
Labels: A: I18N, S: Ready for review

#377 Text strings updated
  po/plume.pot
Labels: A: I18N, S: Ready for review

#374 Use Rust for the front-end too
  .gitignore
  .travis.yml
  Cargo.lock
  Cargo.toml
  Dockerfile
  build.rs
  plume-front/Cargo.toml
  plume-front/src/main.rs
  po/de.po
  po/en.po
  po/fr.po
  po/gl.po
  po/it.po
  po/ja.po
  po/nb.po
  po/pl.po
  po/ru.po
  static/js/autoExpand.js
  static/js/menu.js
  static/js/search.js
  templates/base.rs.html
  templates/posts/new.rs.html
  templates/search/index.rs.html
Labels: A: Front-End, C: Enhancement, S: Ready for review

#386 Trim email and username
  src/routes/user.rs
Labels: A: Backend, C: Bug, S: Ready for review

#392 Avoid panics
  plume-cli/src/instance.rs
  plume-cli/src/search.rs
  plume-cli/src/users.rs
  plume-common/src/activity_pub/inbox.rs
  plume-common/src/activity_pub/mod.rs
  plume-common/src/activity_pub/request.rs
  plume-common/src/activity_pub/sign.rs
  plume-models/src/api_tokens.rs
  plume-models/src/apps.rs
  plume-models/src/blog_authors.rs
  plume-models/src/blogs.rs
  plume-models/src/comment_seers.rs
  plume-models/src/comments.rs
  plume-models/src/db_conn.rs
  plume-models/src/follows.rs
  plume-models/src/instance.rs
  plume-models/src/lib.rs
  plume-models/src/likes.rs
  plume-models/src/medias.rs
  plume-models/src/mentions.rs
  plume-models/src/notifications.rs
  plume-models/src/post_authors.rs
  plume-models/src/posts.rs
  plume-models/src/reshares.rs
  plume-models/src/search/mod.rs
  plume-models/src/search/searcher.rs
  plume-models/src/tags.rs
  plume-models/src/users.rs
  src/api/mod.rs
  src/inbox.rs
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/errors.rs
  src/routes/instance.rs
  src/routes/likes.rs
  src/routes/medias.rs
  src/routes/mod.rs
  src/routes/notifications.rs
  src/routes/posts.rs
  src/routes/reshares.rs
  src/routes/session.rs
  src/routes/tags.rs
  src/routes/user.rs
  src/routes/well_known.rs
  templates/medias/details.rs.html
  templates/medias/index.rs.html
  templates/notifications/index.rs.html
  templates/partials/comment.rs.html
  templates/partials/post_card.rs.html
Labels: A: Backend, C: Enhancement, S: Ready for review
