Repository Plume-org/Plume, pull requests merged in 2019-08, with the labels that each got.

#643 update dependancies
  Cargo.lock
  Cargo.toml
  plume-cli/Cargo.toml
  plume-common/Cargo.toml
  plume-front/Cargo.toml
  plume-models/Cargo.toml
Labels: A: Meta, A: Security, S: Ready for review

#647 Fix theme caching
  Cargo.lock
  src/routes/mod.rs
Labels: A: Backend, C: Bug, S: Ready for review

#656 don't index drafts
  plume-models/src/search/searcher.rs
Labels: A: Backend, C: Bug, S: Ready for review

#659 update default license
  plume-models/src/instance.rs
  src/routes/instance.rs
Labels: A: Backend, C: Bug, S: Ready for review

#657 fill entirely user on creation
  plume-models/src/users.rs
Labels: A: Backend, C: Bug, S: Ready for review

#660 order media so that latest added are top
  plume-models/src/medias.rs
Labels: A: Front-End, C: Enhancement, S: Ready for review
