Repository Plume-org/Plume, pull requests merged in 2019-04, with the labels that each got.

#512 Grammar corrections followup to #510
  plume-front/src/editor.rs
  po/plume/ar.po
  po/plume/de.po
  po/plume/en.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ru.po
  src/mail.rs
  src/main.rs
  src/routes/session.rs
  templates/instance/about.rs.html
  templates/session/login.rs.html
Labels: A: I18N

#486 Editor improvements
  plume-front/src/editor.rs
  po/plume-front/en.po
  po/plume-front/fr.po
  po/plume-front/plume-front.pot
  po/plume/ar.po
  po/plume/de.po
  po/plume/en.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ru.po
  static/css/_article.scss
  static/css/_header.scss
  templates/posts/new.rs.html
Labels: A: Front-End, C: Enhancement, S: Ready for review

#513 Add tests for plume webserver
  .circleci/config.yml
  .circleci/images/plume-buildenv/Caddyfile
  .circleci/images/plume-buildenv/Dockerfile
  .circleci/images/plume-buildenv/cargo_config
  .gitignore
  Cargo.toml
  plume-models/src/config.rs
  script/browser_test/__init__.py
  script/browser_test/instance.py
  script/browser_test/utils.py
  script/run_browser_test.sh
  script/run_unit_test.sh
  script/upload_coverage.sh
  src/main.rs
  src/routes/likes.rs
  src/routes/reshares.rs
  src/test_routes.rs
Labels: A: Backend, A: Front-End, C: Feature, S: Ready for review

#515 Run cargo fmt on plume-front
  plume-front/src/editor.rs
Labels: A: Meta, C: Enhancement, S: Ready for review

#516 Fix tabs on user page
  templates/users/followed.rs.html
  templates/users/followers.rs.html
Labels: A: Front-End, C: Bug, S: Ready for review

#518 Fix Atom feed link on user page
  templates/users/details.rs.html
Labels: A: Front-End, C: Bug

#520 Standard smallest screen is 600px
  static/css/_header.scss
  static/css/main.scss
Labels: A: Front-End, C: Enhancement

#443 Big refactoring of the Inbox
  Cargo.lock
  Cargo.toml
  plume-common/Cargo.toml
  plume-common/src/activity_pub/inbox.rs
  plume-common/src/activity_pub/mod.rs
  plume-common/src/lib.rs
  plume-models/Cargo.toml
  plume-models/src/blogs.rs
  plume-models/src/comments.rs
  plume-models/src/follows.rs
  plume-models/src/inbox.rs
  plume-models/src/lib.rs
  plume-models/src/likes.rs
  plume-models/src/medias.rs
  plume-models/src/mentions.rs
  plume-models/src/plume_rocket.rs
  plume-models/src/posts.rs
  plume-models/src/reshares.rs
  plume-models/src/search/mod.rs
  plume-models/src/users.rs
  plume_test
  plume_tests
  po/plume/ar.po
  po/plume/de.po
  po/plume/en.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ru.po
  src/api/mod.rs
  src/api/posts.rs
  src/inbox.rs
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/instance.rs
  src/routes/likes.rs
  src/routes/mod.rs
  src/routes/posts.rs
  src/routes/reshares.rs
  src/routes/session.rs
  src/routes/user.rs
  src/routes/well_known.rs
Labels: A: Backend, A: Federation, C: Enhancement, S: Ready for review

#519 Add support for remote interact
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  plume-models/src/users.rs
  po/plume/ar.po
  po/plume/de.po
  po/plume/en.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ru.po
  src/main.rs
  src/routes/instance.rs
  src/routes/mod.rs
  src/routes/posts.rs
  src/routes/user.rs
  static/css/_forms.scss
  templates/posts/details.rs.html
  templates/posts/remote_interact.rs.html
  templates/remote_interact_base.rs.html
  templates/users/follow_remote.rs.html
  templates/users/header.rs.html
Labels: A: Federation, C: Feature, S: Ready for review

#528 try to build release plume&plm on ci
  .circleci/config.yml
  script/generate_artifact.sh
Labels: S: Ready for review

#533 strip binary before packing
  script/generate_artifact.sh
Labels: S: Ready for review

#532 Fix #504
  static/css/main.scss
  templates/blogs/details.rs.html
  templates/instance/federated.rs.html
  templates/instance/feed.rs.html
  templates/instance/local.rs.html
Labels: A: Front-End, C: Bug, S: Ready for review

#529 Version bump: 0.3.0 (alpha 2)
  Cargo.toml
  plume-api/Cargo.toml
  plume-cli/Cargo.toml
  plume-common/Cargo.toml
  plume-front/Cargo.toml
  plume-models/Cargo.toml
Labels: A: Meta, S: Ready for review

#535 Remove r
  templates/blogs/details.rs.html
Labels: A: Front-End, P: Low, S: Ready for review

#539 Upload artifacts to plume-ci
  .circleci/config.yml
  script/upload_test_environment.sh
Labels: A: Meta, C: Enhancement, S: Ready for review

#551 Federate user deletion
  Cargo.lock
  plume-models/src/inbox.rs
  plume-models/src/users.rs
  po/plume/ar.po
  po/plume/bg.po
  po/plume/ca.po
  po/plume/cs.po
  po/plume/de.po
  po/plume/en.po
  po/plume/eo.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/hi.po
  po/plume/hr.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ro.po
  po/plume/ru.po
  po/plume/sk.po
  po/plume/sr.po
  po/plume/sv.po
  src/routes/instance.rs
  src/routes/user.rs
Labels: A: Federation, C: Enhancement, S: Ready for review

#540 Remove Canapi
  Cargo.lock
  Cargo.toml
  plume-api/Cargo.toml
  plume-api/src/apps.rs
  plume-api/src/lib.rs
  plume-api/src/posts.rs
  plume-models/Cargo.toml
  plume-models/src/apps.rs
  plume-models/src/lib.rs
  plume-models/src/posts.rs
  src/api/apps.rs
  src/api/mod.rs
  src/api/posts.rs
  src/main.rs
Labels: A: API, C: Enhancement, S: Ready for review

#555 import migrations and don't require diesel_cli for admins
  .circleci/images/plume-buildenv/Dockerfile
  Cargo.lock
  Cargo.toml
  Dockerfile
  migrations/postgres/2019-04-28-201506_create_tantivy_index/down.sql
  migrations/postgres/2019-04-28-201506_create_tantivy_index/up.sql
  migrations/sqlite/2019-04-28-201506_create_tantivy_index/down.sql
  migrations/sqlite/2019-04-28-201506_create_tantivy_index/up.sql
  plume-cli/src/main.rs
  plume-cli/src/migration.rs
  plume-cli/src/search.rs
  plume-macro/Cargo.toml
  plume-macro/src/lib.rs
  plume-models/Cargo.toml
  plume-models/src/lib.rs
  plume-models/src/migrations.rs
  plume-models/src/search/searcher.rs
  plume-models/tests/lib.rs
  script/generate_artifact.sh
  script/run_browser_test.sh
  script/run_unit_test.sh
  src/main.rs
Labels: A: Backend, C: Enhancement, S: Ready for review

#556 remove the new index lock tantivy uses
  plume-cli/src/search.rs
Labels: A: Backend, C: Bug, S: Ready for review

#552 Add some feedback when performing some actions
  plume-models/src/plume_rocket.rs
  po/plume/ar.po
  po/plume/bg.po
  po/plume/ca.po
  po/plume/cs.po
  po/plume/de.po
  po/plume/en.po
  po/plume/eo.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/hi.po
  po/plume/hr.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ro.po
  po/plume/ru.po
  po/plume/sk.po
  po/plume/sr.po
  po/plume/sv.po
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/errors.rs
  src/routes/instance.rs
  src/routes/medias.rs
  src/routes/notifications.rs
  src/routes/posts.rs
  src/routes/search.rs
  src/routes/session.rs
  src/routes/tags.rs
  src/routes/user.rs
  src/template_utils.rs
  static/css/_header.scss
  static/css/_variables.scss
  templates/base.rs.html
Labels: A: Front-End, C: Enhancement, Design, S: Ready for review

#557 reduce reqwest timeout to 5s
  plume-common/src/activity_pub/inbox.rs
  plume-common/src/activity_pub/mod.rs
  plume-models/src/users.rs
Labels: A: Backend, A: Federation, S: Ready for review
