Repository Plume-org/Plume, pull requests merged in 2019-06, with the labels that each got.

#614 add enum containing all successful route returns
  src/routes/blogs.rs
  src/routes/instance.rs
  src/routes/medias.rs
  src/routes/mod.rs
  src/routes/posts.rs
  src/routes/session.rs
  src/routes/user.rs
Labels: A: Backend, S: Ready for review

#616 Update some documents
  CODE_OF_CONDUCT.md
  ISSUE_TEMPLATE.md
  README.md
Labels: A: Meta, C: Enhancement, P: Low, S: Ready for review

#620 Use futures and tokio to send activities
  Cargo.lock
  plume-common/Cargo.toml
  plume-common/src/activity_pub/mod.rs
  plume-common/src/lib.rs
Labels: A: Federation, C: Enhancement, P: Medium
