Repository Plume-org/Plume, pull requests merged in 2019-03, with the labels that each got.

#456 Update dependencies
  Cargo.lock
  plume-models/Cargo.toml
  po/plume/es.po
Labels: C: Enhancement, S: Ready for review

#459 Make media extension parsing safer
  src/routes/medias.rs
Labels: A: Backend, A: Security, C: Enhancement, S: Ready for review

#452 Slightly improve the media experience
  .editorconfig
  plume-models/src/medias.rs
  plume-models/src/safe_string.rs
  po/plume/ar.po
  po/plume/de.po
  po/plume/en.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ru.po
  src/routes/medias.rs
  static/css/_global.scss
  static/images/audio-file.svg
  static/images/unknown-file.svg
  static/images/video-file.svg
  templates/medias/details.rs.html
  templates/medias/index.rs.html
  templates/partials/post_card.rs.html
  templates/posts/new.rs.html
  templates/users/dashboard.rs.html
  templates/users/edit.rs.html
Labels: A: Front-End, C: Enhancement, S: Ready for review

#457 Add a fqn field to blogs and users
  migrations/postgres/2019-03-05-082814_add_fqn/down.sql
  migrations/postgres/2019-03-05-082814_add_fqn/up.sql
  migrations/sqlite/2019-03-05-082846_add_fqn/down.sql
  migrations/sqlite/2019-03-05-082846_add_fqn/up.sql
  plume-models/src/blogs.rs
  plume-models/src/mentions.rs
  plume-models/src/notifications.rs
  plume-models/src/posts.rs
  plume-models/src/schema.rs
  plume-models/src/search/searcher.rs
  plume-models/src/users.rs
  po/plume/ar.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ru.po
  src/api/mod.rs
  src/routes/blogs.rs
  src/routes/posts.rs
  src/routes/session.rs
  src/routes/user.rs
  src/routes/well_known.rs
  src/template_utils.rs
  templates/blogs/details.rs.html
  templates/instance/about.rs.html
  templates/instance/users.rs.html
  templates/partials/comment.rs.html
  templates/partials/post_card.rs.html
  templates/posts/details.rs.html
  templates/users/details.rs.html
  templates/users/followed.rs.html
  templates/users/followers.rs.html
  templates/users/header.rs.html
Labels: A: Backend, C: Enhancement, S: Ready for review

#464 Fix wrong condition, resulting in 404 for valid NodeInfo endpoints
  src/routes/instance.rs
Labels: A: Backend, A: Federation, C: Bug

#471 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: A: Meta, C: Enhancement

#473 Remove some unused #[derive]
  Cargo.lock
  Cargo.toml
  plume-common/src/activity_pub/mod.rs
  plume-models/Cargo.toml
  plume-models/src/blogs.rs
  plume-models/src/comment_seers.rs
  plume-models/src/comments.rs
  plume-models/src/follows.rs
  plume-models/src/instance.rs
  plume-models/src/lib.rs
  plume-models/src/medias.rs
  plume-models/src/mentions.rs
  plume-models/src/notifications.rs
  plume-models/src/posts.rs
  plume-models/src/reshares.rs
  plume-models/src/tags.rs
  plume-models/src/users.rs
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/instance.rs
  src/routes/posts.rs
  src/routes/session.rs
  src/routes/user.rs
Labels: A: Backend, C: Enhancement

#476 Added coloration for selections
  static/css/_global.scss
  static/css/_variables.scss
Labels: A: Front-End, C: Enhancement

#458 New editor
  .gitignore
  Cargo.lock
  Cargo.toml
  build.rs
  plume-front/Cargo.toml
  plume-front/src/editor.rs
  plume-front/src/main.rs
  po/plume-front/en.po
  po/plume-front/fr.po
  po/plume-front/plume-front.pot
  po/plume/ar.po
  po/plume/de.po
  po/plume/en.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ru.po
  static/css/_article.scss
  templates/posts/new.rs.html
Labels: A: Front-End, C: Enhancement, S: Ready for review

#480 Caching
  build.rs
  src/main.rs
  src/routes/mod.rs
  src/template_utils.rs
  static/css/main.scss
  templates/base.rs.html
Labels: A: Backend, C: Enhancement, S: Ready for review

#484 Display error message when signin up with unmatching password
  templates/users/new.rs.html
Labels: A: Front-End, C: Enhancement, S: Ready for review

#482 Add markdown support for summary
  migrations/postgres/2019-03-16-143637_summary-md/down.sql
  migrations/postgres/2019-03-16-143637_summary-md/up.sql
  migrations/sqlite/2019-03-16-143637_summary-md/down.sql
  migrations/sqlite/2019-03-16-143637_summary-md/up.sql
  plume-models/src/schema.rs
  plume-models/src/users.rs
  src/routes/user.rs
  templates/posts/details.rs.html
  templates/users/edit.rs.html
  templates/users/followed.rs.html
  templates/users/followers.rs.html
  templates/users/header.rs.html
Labels: A: Front-End, C: Enhancement, S: Ready for review

#462 Refactor with the help of Clippy
  .travis.yml
  plume-cli/src/search.rs
  plume-front/src/editor.rs
  plume-front/src/main.rs
  plume-models/src/api_tokens.rs
  plume-models/src/lib.rs
  plume-models/src/medias.rs
  plume-models/src/posts.rs
  plume-models/src/safe_string.rs
  plume-models/src/search/mod.rs
  plume-models/src/search/query.rs
  plume-models/src/search/searcher.rs
  plume-models/src/users.rs
  src/api/mod.rs
  src/inbox.rs
  src/mail.rs
  src/main.rs
  src/routes/blogs.rs
  src/routes/medias.rs
  src/routes/mod.rs
  src/routes/posts.rs
  src/routes/search.rs
  src/routes/session.rs
  src/routes/user.rs
  src/template_utils.rs
  templates/blogs/details.rs.html
  templates/instance/federated.rs.html
  templates/instance/local.rs.html
  templates/medias/details.rs.html
  templates/partials/comment.rs.html
  templates/partials/home_feed.rs.html
  templates/posts/details.rs.html
  templates/posts/new.rs.html
  templates/users/header.rs.html
Labels: C: Enhancement, S: Ready for review

#494 Centralize configuration and add some new config
  plume-cli/src/main.rs
  plume-cli/src/search.rs
  plume-models/src/blogs.rs
  plume-models/src/config.rs
  plume-models/src/follows.rs
  plume-models/src/lib.rs
  plume-models/src/posts.rs
  plume-models/src/users.rs
  plume-models/tests/lib.rs
  src/main.rs
  src/routes/session.rs
  src/routes/well_known.rs
Labels: A: Backend, C: Feature, S: Incomplete

#497 Allow to change logo from .env
  Cargo.lock
  plume-models/Cargo.toml
  plume-models/src/config.rs
  plume-models/src/lib.rs
  src/routes/instance.rs
  templates/base.rs.html
Labels: A: Backend, C: Feature, S: Ready for review

#460 Edit blogs, and add blog icons and banners
  migrations/postgres/2019-03-06-115158_blog_images/down.sql
  migrations/postgres/2019-03-06-115158_blog_images/up.sql
  migrations/sqlite/2019-03-19-191712_blog_images/down.sql
  migrations/sqlite/2019-03-19-191712_blog_images/up.sql
  plume-cli/src/search.rs
  plume-common/src/utils.rs
  plume-models/src/blogs.rs
  plume-models/src/comments.rs
  plume-models/src/config.rs
  plume-models/src/follows.rs
  plume-models/src/instance.rs
  plume-models/src/lib.rs
  plume-models/src/posts.rs
  plume-models/src/schema.rs
  plume-models/src/users.rs
  plume-models/tests/lib.rs
  po/plume/ar.po
  po/plume/de.po
  po/plume/en.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ru.po
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/posts.rs
  static/css/_forms.scss
  static/css/_global.scss
  templates/blogs/details.rs.html
  templates/blogs/edit.rs.html
  templates/partials/image_select.rs.html
  templates/posts/details.rs.html
  templates/posts/new.rs.html
  templates/users/dashboard.rs.html
Labels: A: Backend, A: Front-End, C: Feature, S: Ready for review

#502 Always use GMT as a timezone for federation
  plume-common/src/activity_pub/request.rs
Labels: A: Federation, C: Bug, S: Ready for review

#499 Delete notifications when deleting comments
  plume-models/src/comments.rs
  plume-models/src/config.rs
  plume-models/src/notifications.rs
  src/routes/comments.rs
Labels: A: Backend, C: Enhancement, S: Ready for review
