Repository Plume-org/Plume, pull requests merged in 2019-01, with the labels that each got.

#406 Add new subcomand for plm to reset password
  plume-cli/src/users.rs
  plume-models/src/users.rs
Labels: A: Backend, C: Enhancement, S: Ready for review

#409 Encode redirect messages into valid url data
  plume-common/src/utils.rs
Labels: C: Bug, S: Ready for review

#399 Support blind key rotation
  plume-models/src/users.rs
  src/routes/comments.rs
  src/routes/instance.rs
  src/routes/posts.rs
  src/routes/user.rs
Labels: A: Backend, A: Federation, A: Security, C: Feature, S: Ready for review

#430 Better big form handling
  plume-front/src/main.rs
  src/main.rs
  src/routes/errors.rs
  src/routes/mod.rs
  src/routes/posts.rs
  templates/errors/unprocessable_entity.rs.html
  templates/posts/new.rs.html
Labels: A: Backend, C: Bug, S: Incomplete

#375 Improve search UI
  .buildconfig
  po/de.po
  po/en.po
  po/fr.po
  po/gl.po
  po/it.po
  po/ja.po
  po/nb.po
  po/pl.po
  po/plume.pot
  po/ru.po
  src/routes/search.rs
  templates/base.rs.html
  templates/search/index.rs.html
  templates/search/result.rs.html
Labels: A: Front-End, A: I18N, C: Enhancement, S: Ready for review
