Repository Plume-org/Plume, pull requests merged in 2019-02, with the labels that each got.

#440 Update dependencies
  Cargo.lock
  Cargo.toml
  plume-models/src/lib.rs
  src/routes/medias.rs
Labels: C: Enhancement, S: Ready for review

#439 Pull i18n from Funkwhale's weblate
  po/plume/ar.po
  po/plume/en.po
  po/plume/es.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pt.po
  src/main.rs
Labels: A: I18N

#446 Update nodeinfo
  Cargo.toml
  src/routes/instance.rs
  src/routes/well_known.rs
Labels: A: Federation, C: Enhancement

#448 Password reset
  Cargo.lock
  Cargo.toml
  po/plume/ar.po
  po/plume/de.po
  po/plume/en.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ru.po
  src/mail.rs
  src/main.rs
  src/routes/session.rs
  templates/session/login.rs.html
  templates/session/password_reset.rs.html
  templates/session/password_reset_request.rs.html
  templates/session/password_reset_request_ok.rs.html
Labels: A: Backend, C: Feature, S: Ready for review
