Repository Plume-org/Plume, pull requests merged in 2019-09, with the labels that each got.

#664 Fix logo URL
  README.md
Labels: A: Meta, S: Ready for review

#658 delete notification on user deletion
  plume-models/src/notifications.rs
  plume-models/src/users.rs
Labels: A: Backend, C: Bug

#619 Make a distinction between moderators and admins
  assets/themes/default/_forms.scss
  migrations/postgres/2019-06-18-152700_moderator_role/down.sql
  migrations/postgres/2019-06-18-152700_moderator_role/up.sql
  migrations/sqlite/2019-06-18-175952_moderator_role/down.sql
  migrations/sqlite/2019-06-18-175952_moderator_role/up.sql
  migrations/sqlite/2019-06-21-154916_themes/down.sql
  plume-cli/src/users.rs
  plume-models/Cargo.toml
  plume-models/src/admin.rs
  plume-models/src/instance.rs
  plume-models/src/lib.rs
  plume-models/src/schema.rs
  plume-models/src/users.rs
  po/plume/ar.po
  po/plume/bg.po
  po/plume/ca.po
  po/plume/cs.po
  po/plume/de.po
  po/plume/en.po
  po/plume/eo.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/hi.po
  po/plume/hr.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ro.po
  po/plume/ru.po
  po/plume/sk.po
  po/plume/sr.po
  po/plume/sv.po
  src/main.rs
  src/routes/instance.rs
  src/routes/user.rs
  templates/base.rs.html
  templates/instance/admin_mod.rs.html
  templates/instance/users.rs.html
  templates/users/edit.rs.html
  templates/users/header.rs.html
Labels: A: Backend, A: Front-End, C: Enhancement
