Repository Plume-org/Plume, pull requests merged in 2019-05, with the labels that each got.

#558 rewrite circleci config
  .circleci/config.yml
  .circleci/images/plume-buildenv/Dockerfile
  .circleci/images/plume-buildenv/cargo_config
  crowdin.yml
  plume-macro/src/lib.rs
  script/run_browser_test.sh
  script/run_unit_test.sh
  script/upload_coverage.sh
Labels: A: Meta, S: Ready for review

#561 Improve notification management
  plume-models/src/comments.rs
  plume-models/src/follows.rs
  plume-models/src/likes.rs
  plume-models/src/mentions.rs
  plume-models/src/reshares.rs
  src/routes/comments.rs
Labels: A: Backend, C: Enhancement, S: Ready for review

#562 make hashtags work in profile summary
  plume-common/src/utils.rs
  plume-models/src/comments.rs
  plume-models/src/instance.rs
  plume-models/src/posts.rs
  plume-models/src/users.rs
  src/api/posts.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/posts.rs
Labels: A: Front-End, C: Enhancement, S: Ready for review

#560 Fix certain improper rendering of forms
  static/css/_article.scss
  static/css/_forms.scss
  static/css/_global.scss
  static/css/_header.scss
  static/css/main.scss
  templates/search/index.rs.html
  templates/search/result.rs.html
Labels: A: Front-End, Rendering

#571 upload artifact of wasm binary
  .circleci/config.yml
  script/generate_artifact.sh
Labels: A: Front-End, Build, S: Ready for review

#568 use openssl instead of sha256sum for build.rs
  build.rs
Labels: Build, S: Ready for review

#572 cache local instance
  plume-cli/src/main.rs
  plume-cli/src/users.rs
  plume-models/src/blogs.rs
  plume-models/src/comments.rs
  plume-models/src/instance.rs
  plume-models/src/medias.rs
  plume-models/src/posts.rs
  plume-models/src/tags.rs
  plume-models/src/users.rs
  src/api/posts.rs
  src/main.rs
  src/routes/blogs.rs
  src/routes/comments.rs
  src/routes/instance.rs
  src/routes/posts.rs
  src/routes/user.rs
  templates/blogs/details.rs.html
  templates/medias/details.rs.html
  templates/medias/index.rs.html
  templates/users/details.rs.html
Labels: A: Backend, S: Ready for review

#574 update dependancies
  Cargo.lock
  Cargo.toml
  plume-cli/Cargo.toml
  plume-common/Cargo.toml
  plume-macro/Cargo.toml
  plume-models/Cargo.toml
Labels: A: Meta, S: Ready for review

#576 Fix Crowdin upload
  .circleci/config.yml
  crowdin.yml
  po/plume/ar.po
  po/plume/bg.po
  po/plume/ca.po
  po/plume/cs.po
  po/plume/de.po
  po/plume/en.po
  po/plume/eo.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/hi.po
  po/plume/hr.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ro.po
  po/plume/ru.po
  po/plume/sk.po
  po/plume/sr.po
  po/plume/sv.po
Labels: A: I18N, A: Meta, S: Ready for review

#578 Fix occurrences of 'have been' to 'has been'
  src/routes/comments.rs
  src/routes/medias.rs
  src/routes/posts.rs
  src/routes/user.rs
Labels: A: I18N, S: Ready for review

#553 Theme update
  Cargo.lock
  build.rs
  plume-front/Cargo.toml
  po/plume/ar.po
  po/plume/bg.po
  po/plume/ca.po
  po/plume/cs.po
  po/plume/de.po
  po/plume/en.po
  po/plume/eo.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/hi.po
  po/plume/hr.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ro.po
  po/plume/ru.po
  po/plume/sk.po
  po/plume/sr.po
  po/plume/sv.po
  src/main.rs
  src/routes/instance.rs
  static/css/_article.scss
  static/css/_forms.scss
  static/css/_global.scss
  static/css/_header.scss
  static/css/_variables.scss
  static/css/main.scss
  templates/base.rs.html
  templates/blogs/details.rs.html
  templates/instance/about.rs.html
  templates/instance/federated.rs.html
  templates/instance/feed.rs.html
  templates/instance/list.rs.html
  templates/instance/local.rs.html
  templates/instance/privacy.rs.html
  templates/instance/users.rs.html
  templates/medias/details.rs.html
  templates/medias/index.rs.html
  templates/partials/comment.rs.html
  templates/partials/home_feed.rs.html
  templates/partials/instance_description.rs.html
  templates/posts/details.rs.html
Labels: A: Front-End, C: Enhancement, Design, Rendering, S: Ready for review

#598 refactor code to use Shrinkwraprs and diesel-derive-newtype
  Cargo.lock
  Cargo.toml
  plume-common/Cargo.toml
  plume-common/src/activity_pub/mod.rs
  plume-common/src/lib.rs
  plume-models/Cargo.toml
  plume-models/src/blogs.rs
  plume-models/src/comments.rs
  plume-models/src/follows.rs
  plume-models/src/likes.rs
  plume-models/src/posts.rs
  plume-models/src/reshares.rs
  po/plume/ar.po
  po/plume/bg.po
  po/plume/ca.po
  po/plume/cs.po
  po/plume/de.po
  po/plume/en.po
  po/plume/eo.po
  po/plume/es.po
  po/plume/fr.po
  po/plume/gl.po
  po/plume/hi.po
  po/plume/hr.po
  po/plume/it.po
  po/plume/ja.po
  po/plume/nb.po
  po/plume/pl.po
  po/plume/plume.pot
  po/plume/pt.po
  po/plume/ro.po
  po/plume/ru.po
  po/plume/sk.po
  po/plume/sr.po
  po/plume/sv.po
  src/main.rs
  src/routes/mod.rs
  src/routes/user.rs
Labels: S: Ready for review
